object Versions {
    const val googleServices = "4.3.4"
    const val android = "7.2.1"
    const val gradleVersions = "0.42.0"
    const val kotlin = "1.6.21"
    const val devTools = "1.6.21-1.0.6"
    const val firebaseCrashlytics = "2.8.1"
    const val firebasePerf = "1.4.1"
    const val detect = "1.21.0-RC1"

    const val compose = "1.2.0-rc01"
    const val accompanist = "0.24.11-rc"
    const val hilt = "2.42"
    const val room = "2.5.0-alpha02"
    const val okHttp = "5.0.0-alpha.9"
    const val retrofit = "2.9.0"
    const val hiltNavigationCompose = "1.0.0"
    const val pagingCompose = "1.0.0-alpha15"
    const val moshi = "1.13.0"
    const val leakCanary = "2.9.1"
    const val composeDestinations = "1.6.12-beta"
    const val firebaseBom = "30.1.0"
    const val coilCompose = "2.1.0"
    const val palette = "1.0.0"
    const val splashscreen = "1.0.0-rc01"
    const val constraintLayoutCompose = "1.1.0-alpha02"
    const val lifecycleRuntime = "2.5.0-rc01"
    const val activityCompose = "1.5.0-rc01"
    const val lottieCompose = "5.2.0"
    const val timber = "5.0.1"
    const val chucker = "3.5.2"
    const val camera = "1.2.0-alpha02"
    const val cameraLifecycle = "1.2.0-alpha02"
    const val mlKitTextRecognition = "16.0.0-beta4"

    //Instrumentation Tests
    const val coroutinesTest = "1.6.2"
    const val coreTesting = "2.1.0"
    const val truth = "1.1.3"
    const val mockito = "4.6.1"
    const val hiltAndroidTesting = "2.42"
    const val espresso = "3.5.0-alpha07"

    //Unit Test
    const val mockWebserver = "5.0.0-alpha.9"
    const val jUnit = "4.13.2"
    const val testExtJUnit = "1.1.4-alpha07"
}

