name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Access tmdb api key
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo TMDB_API_KEY=\"TMDB_API_KEY\" >> ./local.properties

      - name: Put google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build project
        run: ./gradlew assemble -PfirebasePerformanceInstrumentationEnabled=true
