name: Android Build

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 23, 26, 29, 30 ]

    steps:
      - uses: actions/checkout@v2

      - name: Access tmdb api key
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo TMDB_API_KEY=\"$TMDB_API_KEY\" >> ./local.properties

      - name: Put google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -Dd > ./app/google-services.json

      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck -PfirebasePerformanceInstrumentationEnabled=false
            
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Access tmdb api key
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo TMDB_API_KEY=\"$TMDB_API_KEY\" >> ./local.properties

      - name: Put google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean assembleRelease -PfirebasePerformanceInstrumentationEnabled=true

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1

        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt