name: Android Build

on: pull_request

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 23, 26, 29, 30 ]

    steps:
      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Access tmdb api key
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: echo TMDB_API_KEY=\"$TMDB_API_KEY\" >> ./local.properties

      - name: Put google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean assembleDebug -PfirebasePerformanceInstrumentationEnabled=false
